[tool.poetry]
name = "task3"
version = "0.1.0"
description = ""
authors = [
    "Enikeev Azat <marateni@gmail.com>",
]
readme = "README"

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^8.2.1"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
